# Generated by Django 6.0.7 on 2026-08-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('amount', models.FloatField()),
                ('type_tr', models.CharField()),
                ('time', models.DateTimeField()),
                ('category', models.CharField()),
                ('res_or_sen', models.CharField()),
                ('regullar', models.BooleanField()),
            ],
        ),
    ]
