# Generated by Django 6.0.7 on 2026-09-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id_admin', models.IntegerField()),
                ('user_id_sub', models.IntegerField()),
            ],
        ),
    ]
